// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lancymagnozoffseymrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhbmN5bWFnbm96b2Zmc2V5bXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjA3MzcsImV4cCI6MjA1Nzc5NjczN30.Arz-NxlCyDXxGCWp6RMpCqEaRXe7gPRH3d2weYES0ds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);